Code/bus_timetable/config/routes.rb
BusTimetable::Application.routes.draw do
  resources :stations, { except: [:show] }
  resources :lines, { except: [:show] }
end

Code/bus_timetable/app/models/line.rb
class Line < ActiveRecord::Base
  validates :number, { uniqueness: true,
                       presence: true }
  has_many :stops
  has_many :stations, { through: :stops }
end

Code/bus_timetable/app/models/station.rb
class Station < ActiveRecord::Base
  validates :number, { uniqueness: true,
                       presence: true }
  has_many :lines, { through: :stops }
end

Code/bus_timetable/app/models/stop.rb
class Stop < ActiveRecord::Base
  belongs_to :line
  belongs_to :station
end

Code/bus_timetable/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Code/bus_timetable/app/controllers/lines_controller.rb
class LinesController < ApplicationController

  def index
    @lines = Line.all
  end

  def new
    @line = Line.new
    @stations = Station.all
    render 'new'
  end

  def create
    @line = Line.create(line_params)
    Station.where({ id: params[:line][:station_ids] }).each do |station|
      @line.stations << station
    end
    if @line.save
      flash[:notice] = 'Line created'
      redirect_to lines_path
    else
      render 'new'
    end
  end

  def destroy
    @line = Line.find(params[:id])
    @line.destroy
    flash[:notice] = 'Line deleted.'
    redirect_to lines_path
  end

  def edit
    @line = Line.find(params[:id])
    @stations = Station.all
  end

  def update
    @line = Line.find(params[:id])
    @line.stations.clear
    Station.where({ id: params[:line][:station_ids] }).each do |station|
      @line.stations << station
    end
    if @line.update(line_params)
      flash[:notice] = 'Line updated.'
      redirect_to lines_path
    else
      render 'edit'
    end
  end

private
  def line_params
    params.require(:line).permit(:number)
  end
end

Code/bus_timetable/app/controllers/stations_controller.rb
class StationsController < ApplicationController

  def index
    @stations = Station.all
  end

  def new
    @lines = Line.all
    @station = Station.new
    render 'new'
  end

  def create
    @lines = Line.all
    @station = Station.new(station_params)
    if @station.save
      flash[:notice] = 'Station created.'
      redirect_to stations_path
    else
      render 'new'
    end
  end

  def destroy
    @station = Station.find(params[:id])
    @station.destroy
    flash[:notice] = 'Station deleted.'
    redirect_to stations_path
  end

  def edit
    @station = Station.find(params[:id])
    @lines = Line.all
  end

  def update
    @station = Station.find(params[:id])
    @lines = Line.all
    if @station.update(station_params)
      flash[:notice] = 'Station updated.'
      redirect_to stations_path
    else
      render 'edit'
    end
  end

private
  def station_params
    params.require(:station).permit(:number)
  end

end

Code/bus_timetable/app/controllers/stops_controller.rb
class Stops < ApplicationController

  def create
    @astronauts = Astronaut.where(:id => params[:astronauts_id])
    @mission = Mission.find(params[:mission_id])
    @astronauts.each do |astronaut|
      astronaut.update(:mission_id => @mission.id)
    end
    render("")
  end
end

Code/bus_timetable/app/helpers/application_helper.rb
module ApplicationHelper
end

Code/bus_timetable/app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

Code/bus_timetable/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : 'Bus Timetable' %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>


  <body>

    <%= yield %>

    <div class='row flash'>
      <%= flash[:alert] %>
      <%= flash[:notice] %>
    </div>

    <%= javascript_include_tag "application" %>
  </body>

</html>

Code/bus_timetable/app/views/lines/_form.html.erb
<%= form_for(@line) do |f| %>
  <div class="row">
    <div class="form-group small-3 column">
      <%= f.label :number %>
      <%= f.text_field :number %>
    </div>
  </div>
  <div class="row">
    <div class="form-group small-2 column">
      <% @stations.each do |station| %>
        <%= check_box_tag "line[station_ids][]", station.id,  @line.station_ids.include?(station.id) %>
        <%= station.number %><br/>
      <% end %>
    </div>
  </div>
  <%= f.submit({ :class => 'button tiny' }) %>
<% end %>

Code/bus_timetable/app/views/lines/edit.html.erb
<%= content_for(:title, 'Edit line | Bus Timetable') %>

<div class='row'>
  <%= render 'layouts/errors', { object: @line } %>

  <h1>Edit Bus Line:</h1>

  <%= render 'form' %>
</div>

Code/bus_timetable/app/views/lines/index.html.erb
<%= content_for(:title, 'Lines | Bus Timetable') %>

<div class="row">
  <h1>Lines</h1>

  <ul>
    <% @lines.sort_by! { |line| line.number } %>
    <% @lines.each do |line| %>
      <li>
        Line #<%= line.number.to_s %> | <%= link_to "Edit", edit_line_path(line), {method: 'get'} %> | <%= link_to "Delete", line_path(line), { confirm: "You sure?", method: 'delete' } %>
      </li>
    <% end %>
  </ul>
  <%= link_to "New Line", new_line_path, { class: "button tiny"} %>
</div>

Code/bus_timetable/app/views/lines/new.html.erb
<%= content_for(:title, 'New line | Bus Timetable') %>

<div class="row">
  <%= render 'layouts/errors', { object: @line } %>

  <h1>New Bus Line</h1>

  <%= render 'form' %>
</div>

Code/bus_timetable/app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <div class="row">
    <div class='form-group small-3 columns'>
      <%= f.label :number %>
      <%= f.text_field :number %>
    </div>
  </div>
  <%= f.submit({ :class => 'button tiny'}) %>
<% end %>

Code/bus_timetable/app/views/stations/edit.html.erb
<%= content_for(:title, 'Edit station | Bus Timetable') %>

  <div class="row">
    <%= render 'layouts/errors', { object: @station } %>

    <h1>Edit Bus Station:</h1>

    <%= render 'form' %>
  </div>

Code/bus_timetable/app/views/stations/index.html.erb
<%= content_for(:title, 'Stations | Bus Timetable') %>

<div class="row">
    <h1>Stations</h1>

  <ul>
    <% @stations.sort_by! { |station| station.number } %>
    <% @stations.each do |station| %>
      <li>Station #<%= station.number.to_s %> | <%= link_to "Edit", edit_station_path(station), { method: 'get' } %> | <%= link_to "Delete", station_path(station), { confirm: 'You sure?', method: 'delete' } %></li>
    <% end %>
  </ul>

  <%= link_to "New station", new_station_path, { class: "button tiny"} %>
</div>

Code/bus_timetable/app/views/stations/new.html.erb
<%= content_for(:title, 'New station | Bus Timetable') %>

  <div class="row">
    <%= render 'layouts/errors', { object: @station } %>

    <h1>New Bus Station:</h1>

    <%= render 'form' %>
  </div>